version: "3.9"

services:
  pihole:
    image: pihole/pihole:latest
    restart: unless-stopped
    container_name: pihole
    network_mode: "host"
    # ports: # Not needed with host networking
    environment:
        # Set the appropriate timezone for your location from
        # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones, e.g:
        TZ: 'Europe/Amsterdam'
        # Set a password to access the web interface. Not setting one will result in a random password being assigned
        FTLCONF_webserver_api_password: 'correct horse battery staple'
        # If using Docker's default `bridge` network setting the dns listening mode should be set to 'all'
        FTLCONF_dns_listeningMode: 'all'
        # Set custom web port to avoid conflict with Caddy
        FTLCONF_webserver_port: '8088'
    # Volumes store your data between container upgrades
    volumes:
        # For persisting Pi-hole's databases and common configuration file
        - '/home/server/server_config/pihole:/etc/pihole'
        # Uncomment the below if you have custom dnsmasq config files that you want to persist. Not needed for most starting fresh with Pi-hole v6. If you're upgrading from v5 you and have used this directory before, you should keep it enabled for the first v6 container start to allow for a complete migration. It can be removed afterwards. Needs environment variable FTLCONF_misc_etc_dnsmasq_d: 'true'
        #- './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
        # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
        # Required if you are using Pi-hole as your DHCP server, else not needed
        - NET_ADMIN
        # Required if you are using Pi-hole as your NTP client to be able to set the host's system time
        - SYS_TIME
        # Optional, if Pi-hole should get some more processing time
        - SYS_NICE